'use strict';
// Pure data helpers also run in Node; never coerce null into a numeric zero.
const finite = v => typeof v === 'number' && Number.isFinite(v);
const arr = v => Array.isArray(v) ? v : [];
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const month = v => { const m = String(v ?? '').match(/^(\d{4})-?(0[1-9]|1[0-2])$/); return m ? `${m[1]}-${m[2]}` : null; };
function monthRange(first,last){ if(!month(first)||!month(last)||first>last)return []; const out=[]; let [y,m]=first.split('-').map(Number); while(`${y}-${String(m).padStart(2,'0')}`<=last && out.length<2400){out.push(`${y}-${String(m).padStart(2,'0')}`);if(++m===13){m=1;y++;}}return out; }
function endingMonths(end,count){end=month(end);if(!end)return [];let [y,m]=end.split('-').map(Number);const d=new Date(Date.UTC(y,m-count,1));return monthRange(`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`,end);}
function cleanSeries(points){const map=new Map();for(const p of arr(points)){const m=month(p?.month);if(m)map.set(m,finite(p.value)?p.value:null);}const keys=[...map.keys()].sort();return keys.length?monthRange(keys[0],keys.at(-1)).map(m=>({month:m,value:map.get(m)??null})):[];}
function itemHistory(item,kind,globalMonths=[]){const values=arr(item[kind]);if(values[0] && typeof values[0]==='object')return cleanSeries(values).slice(kind==='spark'?-12:-36);const labels=kind==='spark'?endingMonths(item.latest_ym,values.length):arr(item.db_months).length?item.db_months:globalMonths;if(labels.length!==values.length)return [];return cleanSeries(values.map((v,i)=>({month:labels[i],value:v}))).slice(kind==='spark'?-12:-36);}
function growth(value,base){return finite(value)&&finite(base)&&base!==0?(value/base-1)*100:null;}
function quarters(points){const groups=new Map();for(const p of cleanSeries(points)){const [y,m]=p.month.split('-').map(Number),q=`${y}Q${Math.ceil(m/3)}`;if(!groups.has(q))groups.set(q,[]);groups.get(q).push(p.value);}return [...groups].map(([quarter,vs])=>({quarter,value:vs.length===3&&vs.every(finite)?vs.reduce((a,b)=>a+b,0)/3:null}));}
function normalize(series){const cleaned=series.map(cleanSeries),all=cleaned.flatMap(s=>s.map(p=>p.month)).sort();if(!all.length)return {base:null,series:cleaned};const months=monthRange(all[0],all.at(-1));const maps=cleaned.map(s=>new Map(s.map(p=>[p.month,p.value])));const base=months.find(m=>maps.every(s=>finite(s.get(m))&&s.get(m)!==0))??null;return {base,series:maps.map(s=>months.map(m=>({month:m,value:base&&finite(s.get(m))?s.get(m)/s.get(base)*100:null})))};}
function segments(values){const out=[];let current=[];values.forEach((v,i)=>{if(finite(v))current.push([i,v]);else if(current.length){out.push(current);current=[];}});if(current.length)out.push(current);return out;}
function csvCell(v){let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+@-]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
const defaults={search:'',company:'',market:'',country:'',flow:'',workbook:'',reference:'',coverage:'',conflict:'',primary:false,favorites:false,sort:'cap',layout:'cards',view:'stocks'};
function stateFrom(params){const out={...defaults};for(const key of Object.keys(out)){const v=params.get(key);if(v!==null)out[key]=typeof out[key]==='boolean'?v==='1':v.slice(0,500);}if(!['stocks','ppi','compare','sources','workbook'].includes(out.view))out.view='stocks';if(!['cards','table','companies'].includes(out.layout))out.layout='cards';if(!['cap','latest','yoy','mom','qoq','yoy3','sym','count'].includes(out.sort))out.sort='cap';return out;}
function stateQuery(state){const q=new URLSearchParams();for(const k of Object.keys(defaults))if(state[k]!==defaults[k])q.set(k,typeof defaults[k]==='boolean'?(state[k]?'1':'0'):state[k]);return q.toString();}
function filterRows(items,s,favorites=[]){const needle=s.search.toLocaleLowerCase();return items.filter(i=>(!needle||[i.sym,i.name,i.product,i.label,i.hs6].some(v=>String(v??'').toLocaleLowerCase().includes(needle)))&&(!s.company||String(i.sym)===s.company)&&(!s.market||i.market===s.market)&&(!s.country||(i.o2||i.origin)===s.country)&&(!s.flow||(i.flow||i.dir)===s.flow)&&(!s.workbook||(i.workbook?.status??'미제공')===s.workbook)&&(!s.reference||(i.st??'미제공')===s.reference)&&(!s.primary||i.primary===true)&&(!s.favorites||favorites.includes(String(i.id)))&&(!s.conflict||(s.conflict==='hs'?i.hs_changed===true:s.conflict==='changed'?i.status_changed===true:!!i.workbook&&i.status_changed===false))&&(!s.coverage||(s.coverage==='company'?i.existing?.company===true:s.coverage==='hs'?i.existing?.hs===true:s.coverage==='new-company'?i.existing?.company===false:s.coverage==='new-hs'?!!i.hs6&&i.existing?.hs===false:s.coverage==='missing-hs'?!i.hs6:!i.existing))).sort((a,b)=>{if(s.sort==='sym')return String(a.sym).localeCompare(String(b.sym));if(s.sort==='count')return items.filter(i=>i.sym===b.sym).length-items.filter(i=>i.sym===a.sym).length;const av=a[s.sort],bv=b[s.sort];return finite(av)&&finite(bv)?bv-av:finite(av)?-1:finite(bv)?1:String(a.id).localeCompare(String(b.id));});}
const ppiDefaults={query:'',country:'',group:'',category:'',sort:'name',language:'ko',stale:true,surge:false,favorite:false,yoy:'',mom:'',qoq:'',layout:'cards',ascending:false,threshold:'10',hot:false,acc:'0'};
function ppiSavedState(value){const out={...ppiDefaults};if(!value||typeof value!=='object'||Array.isArray(value))return out;for(const k of Object.keys(out))if(typeof value[k]===typeof out[k])out[k]=typeof value[k]==='string'?value[k].slice(0,500):value[k];for(const [key,values] of [['sort',['name','last_month','yoy','mom','qoq','yoy3','abs_yoy','acceleration']],['layout',['cards','table']],['language',['ko','en']]])if(!values.includes(out[key]))out[key]=ppiDefaults[key];for(const k of ['yoy','mom','qoq','threshold','acc'])if(out[k]!==''&&!Number.isFinite(Number(out[k])))out[k]=ppiDefaults[k];if(out.threshold===''||Number(out.threshold)<0)out.threshold='10';if(!Number.isInteger(Number(out.acc))||Number(out.acc)<0||Number(out.acc)>6)out.acc='0';return out;}
function validPresets(value){return arr(value).filter(p=>p&&typeof p==='object'&&typeof p.name==='string'&&p.state&&typeof p.state==='object'&&!Array.isArray(p.state)).map(p=>({name:p.name.slice(0,80),state:ppiSavedState(p.state)}));}
const helpers={ppiSavedState,validPresets,finite,esc,month,monthRange,endingMonths,cleanSeries,history:itemHistory,growth,quarters,normalize,segments,csvCell,stateFrom,stateQuery,filterRows};
if(typeof module!=='undefined'&&module.exports)module.exports=helpers;
if(typeof window!=='undefined'&&typeof document!=='undefined')boot();
function boot(){
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], data=window.STOCKMAP;
 const say=s=>{$('#message').textContent=s;};
 if(!data||!Array.isArray(data.items)){say('데이터를 불러오지 못했습니다. 같은 폴더의 page-data.js가 window.STOCKMAP을 제공하는지 확인하세요.');$('#filters').hidden=true;return;}
 const items=data.items.filter(i=>i&&typeof i==='object'), ppis=arr(data.ppi?.items).filter(i=>i&&typeof i==='object');
 let state=stateFrom(new URLSearchParams(location.search)),selected=[],returnFocus=null;
 function read(k,fallback){try{return JSON.parse(localStorage.getItem('stockmap:'+k))??fallback;}catch{return fallback;}}
 function save(k,v){try{localStorage.setItem('stockmap:'+k,JSON.stringify(v));}catch{say('로컬 저장이 제한되어 이번 화면에서만 유지됩니다.');}}
 let favorites=read('favorites',[]),presets=read('presets',[]);if(!Array.isArray(favorites))favorites=[];if(!Array.isArray(presets))presets=[];presets=presets.filter(p=>p&&typeof p.name==='string'&&p.state&&typeof p.state==='object');
 const theme=read('theme','light');document.documentElement.dataset.theme=theme==='dark'?'dark':'light';
 const fmt=v=>finite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:2}):'—';
 const cap=v=>!finite(v)?'—':v>=1e12?`$${fmt(v/1e12)}T`:v>=1e9?`$${fmt(v/1e9)}B`:`$${fmt(v/1e6)}M`;
 const pct=v=>finite(v)?`${fmt(v)}%`:'—';
 const text=v=>typeof v==='object'?JSON.stringify(v,null,2):String(v??'미제공');
 const raw=v=>`<pre>${esc(text(v))}</pre>`;
 const empty=s=>`<p class="empty">${esc(s)}</p>`;
 const link=(url,label)=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(label);}catch{return esc(label);}};
 function options(values){return '<option value="">전체</option>'+[...new Set(values.filter(v=>v!=null&&v!==''))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');}
 const filterSpecs=[['company','회사',items.map(i=>i.sym)],['market','시장',items.map(i=>i.market)],['country','국가 코드',items.map(i=>i.o2||i.origin)],['flow','무역 방향',items.map(i=>i.flow||i.dir)],['workbook','워크북 원문 상태',items.map(i=>i.workbook?.status??'미제공')],['reference','참조 원문 상태',items.map(i=>i.st??'미제공')]];
 $('#select-filters').innerHTML=filterSpecs.map(([key,label,values])=>`<label>${label}<select data-filter="${key}">${options(values)}</select></label>`).join('')+`<label>기존 자료 연결<select data-filter="coverage"><option value="">전체</option><option value="company">기존 기업</option><option value="new-company">신규 기업</option><option value="hs">기존 HS 구조</option><option value="new-hs">신규 HS</option><option value="missing-hs">HS 코드 없음</option><option value="unknown">확인 정보 없음</option></select></label><label>판본 충돌<select data-filter="conflict"><option value="">전체</option><option value="changed">상태 변경</option><option value="hs">HS 변경</option><option value="same">상태 동일</option></select></label><label>내림차순 정렬<select data-filter="sort">${[['cap','시가총액 스냅샷'],['latest','최근 무역액'],['yoy','YoY'],['mom','MoM'],['qoq','QoQ'],['yoy3','3M YoY'],['sym','종목명'],['count','회사 품목 수']].map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label>`;
 $('#dataset-meta').textContent=`통합 ${data.built??'미제공'} · 참조 ${data.reference?.built??'미제공'} · 워크북 ${data.workbook?.date??'미제공'}`;
 function actions(i){const id=esc(i.id);return `<div class="toolbar"><button data-action="detail" data-id="${id}">근거·시계열</button><button data-action="favorite" data-id="${id}" aria-pressed="${favorites.includes(String(i.id))}">관심</button><button data-action="compare" data-id="${id}" aria-pressed="${selected.includes(String(i.id))}">비교</button></div>`;}
 function badges(i){return `<span class="badge">참조: ${esc(i.st??'미제공')}</span><span class="badge">워크북: ${esc(i.workbook?.status??'미제공')}</span><span class="badge">${esc(month(i.latest_ym)??'월 미제공')}</span>${i.status_changed?'<span class="badge">판본 상태 변경</span>':''}`;}
 function identity(i){return `${i.sym??''} · ${i.o2||i.origin||'국가 미제공'} · ${i.flow||i.dir||''} · HS ${i.hs6??'미제공'} · ${i.id}`;}
 function card(i){return `<article class="card" data-item-id="${esc(i.id)}"><small>${esc(identity(i))}</small><h3>${esc(i.name)}</h3><p class="muted">${esc(i.market)} · 시총 스냅샷 ${cap(i.cap)} · ${esc(data.reference?.built)}</p><p>${esc(i.label||i.product)}</p>${badges(i)}<div class="metrics"><div>최근 (천 USD)<strong>${fmt(i.latest)}</strong></div><div>YoY<strong>${pct(i.yoy)}</strong></div><div>MoM<strong>${pct(i.mom)}</strong></div><div>QoQ<strong>${pct(i.qoq)}</strong></div><div>3M YoY<strong>${pct(i.yoy3)}</strong></div></div>${sparkline(itemHistory(i,"spark"))}${actions(i)}</article>`;}
 function renderStocks(){const rows=filterRows(items,state,favorites);$('#result-count').textContent=`${new Set(rows.map(i=>i.sym)).size}개 기업 · ${rows.length}개 항목 / 전체 ${items.length}개`;const target=$('#stock-results');target.className=state.layout==='cards'?'cards':'';if(!rows.length){target.innerHTML=empty('조건에 맞는 항목이 없습니다. 필터를 조정하세요.');return;}if(state.layout==='cards')target.innerHTML=rows.map(card).join('');else if(state.layout==='companies'){const groups=new Map();rows.forEach(i=>{if(!groups.has(i.sym))groups.set(i.sym,[]);groups.get(i.sym).push(i);});target.innerHTML=[...groups].map(([sym,rs])=>`<details class="card"><summary>${esc(sym)} · ${esc(rs[0].name)} · ${rs.length}개 품목 · 시총 ${cap(rs[0].cap)} (참고 판본)</summary><div class="cards">${rs.map(card).join('')}</div></details>`).join('');}else target.innerHTML=`<div class="table-wrap"><table><caption>필터 결과 · 무역액 단위 천 USD</caption><thead><tr>${['기업 / 정확한 항목','품목','판본 상태','최근','YoY','MoM','QoQ','3M YoY','동작'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(i=>`<tr data-item-id="${esc(i.id)}"><td>${esc(i.name)}<br>${esc(identity(i))}</td><td>${esc(i.label)}<br>${esc(i.product)}</td><td>${badges(i)}</td><td>${fmt(i.latest)}</td><td>${pct(i.yoy)}</td><td>${pct(i.mom)}</td><td>${pct(i.qoq)}</td><td>${pct(i.yoy3)}</td><td>${actions(i)}</td></tr>`).join('')}</tbody></table></div>`;}
 // A chart axis is assigned by unit, never by series amplitude. Missing slots break paths.
 function staticChart(series,labels,title){if(!labels.length||!series.some(s=>s.values.some(finite)))return empty('표시할 시계열이 없습니다.');const units=[...new Set(series.map(s=>s.unit))],colors=['#159b86','#d78725','#6982e8','#c958a0'];const scales=units.map(u=>{const vs=series.filter(s=>s.unit===u).flatMap(s=>s.values).filter(finite);let lo=Math.min(0,...vs),hi=Math.max(0,...vs);if(lo===hi)hi=lo+1;return {lo,hi};});const x=i=>90+(labels.length===1?310:i/(labels.length-1)*620),y=(v,u)=>{const s=scales[units.indexOf(u)];return 225-(v-s.lo)/(s.hi-s.lo)*170;};let svg=`<svg class="chart" viewBox="0 0 820 275" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title>`;for(let t=0;t<=4;t++){const yy=55+t*42.5;svg+=`<line class="grid" x1="90" x2="710" y1="${yy}" y2="${yy}"/>`;units.forEach((u,j)=>{const s=scales[j];svg+=`<text x="${j?720:80}" y="${yy+4}" text-anchor="${j?'start':'end'}">${esc(fmt(s.hi-(s.hi-s.lo)*t/4))}</text>`;});}units.forEach((u,j)=>{svg+=`<text x="${j?710:90}" y="22" text-anchor="${j?'end':'start'}">${j?'오른쪽':'왼쪽'}: ${esc(u)}</text>`;});series.forEach((s,j)=>{for(const seg of segments(s.values)){svg+=`<path fill="none" stroke="${colors[j%4]}" stroke-width="2.5" d="${seg.map(([i,v],k)=>`${k?'L':'M'}${x(i)},${y(v,s.unit)}`).join(' ')}"/>`;}s.values.forEach((v,i)=>{if(finite(v))svg+=`<circle cx="${x(i)}" cy="${y(v,s.unit)}" r="3" fill="${colors[j%4]}"><title>${esc(s.name)} / ${esc(labels[i])}: ${esc(fmt(v))} ${esc(s.unit)}</title></circle>`;});});[...new Set([0,Math.floor((labels.length-1)/2),labels.length-1])].forEach(i=>{svg+=`<text x="${x(i)}" y="252" text-anchor="middle">${esc(labels[i])}</text>`;});svg+='</svg>';return svg+`<div class="legend">${series.map((s,j)=>`<span style="color:${colors[j%4]}">● ${esc(s.name)} (${esc(s.unit)})</span>`).join('')}</div><details><summary>차트 수치 표</summary><div class="table-wrap"><table><thead><tr><th scope="col">기간</th>${series.map(s=>`<th scope="col">${esc(s.name)} (${esc(s.unit)})</th>`).join('')}</tr></thead><tbody>${labels.map((m,i)=>`<tr><th scope="row">${esc(m)}</th>${series.map(s=>`<td>${fmt(s.values[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`;}
 const chartWindows=new Map();let chartSerial=0;
 function chart(series,labels,title){if(!labels.length)return staticChart(series,labels,title);const key=String(++chartSerial);chartWindows.set(key,{series,labels,title});if(chartWindows.size>100)chartWindows.delete(chartWindows.keys().next().value);const opts=selected=>labels.map((m,n)=>`<option value="${n}" ${n===selected?'selected':''}>${esc(m)}</option>`).join('');return `<section data-chart-window="${key}"><div class="toolbar"><label>시작 기간<select data-chart-bound="start">${opts(0)}</select></label><label>끝 기간<select data-chart-bound="end">${opts(labels.length-1)}</select></label><button data-chart-reset>전체 기간</button></div><div data-chart-content>${staticChart(series,labels,title)}</div></section>`;}
 function redrawWindow(box,reset=false){const spec=chartWindows.get(box.dataset.chartWindow);if(!spec)return;const a=box.querySelector('[data-chart-bound="start"]'),b=box.querySelector('[data-chart-bound="end"]');if(reset){a.value='0';b.value=String(spec.labels.length-1);}const start=Number(a.value),end=Number(b.value);box.querySelector('[data-chart-content]').innerHTML=start>end?empty('시작 기간이 끝 기간보다 늦습니다.'):staticChart(spec.series.map(v=>({...v,values:v.values.slice(start,end+1)})),spec.labels.slice(start,end+1),spec.title);}
 document.addEventListener('change',e=>{if(e.target.matches('[data-chart-bound]'))redrawWindow(e.target.closest('[data-chart-window]'));});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-chart-reset]');if(b)redrawWindow(b.closest('[data-chart-window]'),true);});
 function sparkline(points){const ps=cleanSeries(points),vs=ps.map(p=>p.value).filter(finite);if(!vs.length)return '';let lo=Math.min(...vs),hi=Math.max(...vs);if(hi===lo)hi=lo+1;return `<svg class="sparkline" viewBox="0 0 300 55" role="img" aria-label="최근 월별 흐름"><title>최근 월별 흐름 · 결측 구간은 연결하지 않음</title>${segments(ps.map(p=>p.value)).map(seg=>`<path fill="none" stroke="currentColor" stroke-width="2" d="${seg.map(([i,v],j)=>`${j?'L':'M'}${5+i/Math.max(1,ps.length-1)*290},${50-(v-lo)/(hi-lo)*45}`).join(' ')}"/>`).join('')}</svg>`;}
 function seriesChart(points,name,unit){return chart([{name,unit,values:points.map(p=>p.value)}],points.map(p=>p.month),name);}
 function open(title,html){delete $('#detail-dialog').dataset.ppi;returnFocus=document.activeElement;$('#detail-title').textContent=title;$('#detail-body').innerHTML=html;$('#detail-dialog').showModal();$('#close-dialog').focus();}
 function detail(i){const spark=itemHistory(i,'spark',data.months),db=itemHistory(i,'db',data.months);const qs=arr(i.q).filter(Array.isArray).sort((a,b)=>String(a[0]).localeCompare(String(b[0])));let qlabels=[];if(qs.length){const valid=qs.filter(q=>/^\d{4}Q[1-4]$/.test(q[0]));if(valid.length){const a=valid[0][0],b=valid.at(-1)[0];for(let n=Number(a.slice(0,4))*4+Number(a.at(-1))-1,end=Number(b.slice(0,4))*4+Number(b.at(-1))-1;n<=end&&qlabels.length<400;n++)qlabels.push(`${Math.floor(n/4)}Q${n%4+1}`);}}const qm=new Map(qs.map(q=>[q[0],q]));open(`${i.name} · ${i.label||i.hs6}`,`<p>${esc(identity(i))}</p>${badges(i)}<h3>원문 최근 12개월 요약</h3><p>spark: 원문 최근월을 끝으로 하는 요약. HS6 DB와 별도 자료이며 일치한다고 가정하지 않습니다.</p>${seriesChart(spark,'원문 요약','천 USD')}<h3>HS6 월별 원문 DB · 최대 36개월</h3><p>명시된 db_months 또는 제공된 공통 months만 사용합니다. 달력이 없으면 차트를 만들지 않습니다. 원문의 0은 0으로 유지합니다.</p>${seriesChart(db,'HS6 DB','천 USD')}<h3>분기 무역과 KPI</h3><p>${esc(i.kpi_kind)} · ${esc(i.kpi_latest)} · 출처 제공 분기값이며 자체 재검증 전입니다.</p>${chart([{name:'무역',unit:'천 USD',values:qlabels.map(q=>qm.get(q)?.[1]??null)},{name:i.kpi||'KPI',unit:i.kpi_unit||'KPI 단위 미제공',values:qlabels.map(q=>qm.get(q)?.[2]??null)}],qlabels,'분기 무역 및 KPI: 별도 단위 축')}<h3>판본별 근거</h3><div class="evidence"><section><h4>워크북 · ${esc(data.workbook?.date??'날짜 미제공')}</h4>${raw(i.workbook??'워크북 근거 미제공')}</section><section><h4>참조 · ${esc(data.reference?.built??data.built??'날짜 미제공')}</h4>${raw({status:i.st,verification:i.vstatus,source:i.src,hs6:i.hs6,latest_ym:i.latest_ym,latest:i.latest,reason:i.reason,candidates:i.cand})}</section></div><h3>연결·검증 원문 상세</h3>${raw({primary:i.primary,market_cap_usd_snapshot:i.cap,market_cap_edition:data.reference?.built,ratio:i.ratio,share_definition:'원문 정의 미확인; 기업 매출 비중 아님',share:i.share,months:i.months,accel:i.accel,correlation:i.cur_r,lag:i.cur_lag,span:i.cur_span,existing:i.existing})}<h3>별도 공식 수집</h3>${raw(i.official??'공식 수집 자료 미제공')}`);}
 function renderCompare(){const chosen=selected.map(id=>items.find(i=>String(i.id)===id)).filter(Boolean),kind=$('#compare-kind').value;$('#compare-count').textContent=`${chosen.length}/4`;if(!chosen.length){$('#compare-results').innerHTML=empty('탐색 화면에서 비교할 항목을 선택하세요.');return;}const normalized=normalize(chosen.map(i=>itemHistory(i,kind,data.months)));$('#compare-results').innerHTML=chosen.map(i=>`<p>${esc(identity(i))} · ${esc(kind)} <button data-action="remove-compare" data-id="${esc(i.id)}">비교 해제</button></p>`).join('')+`<p>공통 기준월: ${esc(normalized.base??'없음 — 공통 유효·비영 월 필요')}</p>`+chart(chosen.map((i,j)=>({name:identity(i),unit:'기준월=100',values:normalized.series[j].map(p=>p.value)})),normalized.series[0]?.map(p=>p.month)??[],'정규화 시계열 비교');}
 const ppiOptions=ppiDefaults;
 let ppiState={...ppiOptions},ppiPage=0,ppiFavorites=read('ppi-favorites',[]),ppiPresets=read('ppi-presets',[]);
 if(!Array.isArray(ppiFavorites))ppiFavorites=[];
 ppiPresets=validPresets(ppiPresets);
 const ppiTitle=i=>ppiState.language==='en'&&i.name_en?i.name_en:i.name;
 $('#ppi-view').innerHTML=`<h2>생산자물가 PPI</h2><p>참고 ${fmt(data.summary.ppi_reference_series)}개와 기존 Phalanx 관측계열을 함께 탐색합니다. 서로 다른 출처의 같은 계열은 출처별로 유지합니다.</p><div class="filter-grid"><label>검색<input data-ppi="query" type="search" placeholder="품목·영문명·계열 코드"></label><label>국가<select data-ppi="country">${options(ppis.map(i=>i.country))}</select></label><label>산업 그룹<select data-ppi="group">${options(ppis.map(i=>i.group))}</select></label><label>세부 분류<select data-ppi="category">${options(ppis.map(i=>i.category||i.group))}</select></label><label>정렬<select data-ppi="sort">${[['name','이름'],['last_month','최근 월'],['yoy','YoY'],['mom','MoM'],['qoq','QoQ'],['abs_yoy','YoY 절댓값'],['acceleration','6개월 상승 횟수'],['yoy3','3M YoY']].map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>보기<select data-ppi="layout"><option value="cards">카드</option><option value="table">표</option></select></label><label>급등락 기준 |YoY| ≥ (%)<input type="number" min="0" data-ppi="threshold" value="10"></label><label>상승 횟수 ≥ (최근 6개월)<input type="number" min="0" max="6" data-ppi="acc" value="0"></label><label>이름 언어<select data-ppi="language"><option value="ko">한국어</option><option value="en">English (제공 시)</option></select></label>${['yoy','mom','qoq'].map(k=>`<label>최소 ${k.toUpperCase()} (%)<input type="number" step="any" data-ppi="${k}"></label>`).join('')}</div><div class="toolbar"><label><input type="checkbox" data-ppi="stale" checked> 6개월 초과 자료 제외</label><label><input type="checkbox" data-ppi="hot"> 급등락만</label><label><input type="checkbox" data-ppi="surge"> 6개월 모두 상승</label><label><input type="checkbox" data-ppi="ascending"> 낮은 값부터</label><label><input type="checkbox" data-ppi="favorite"> 관심 계열만</label><button id="ppi-reset">조건 초기화</button><button id="ppi-csv">결과 CSV</button></div><div class="toolbar"><label>조건 이름<input id="ppi-preset-name" maxlength="80"></label><button id="ppi-save">저장</button><label>저장 조건<select id="ppi-presets"></select></label><button id="ppi-load">불러오기</button><button id="ppi-delete">삭제</button></div><p id="ppi-count" role="status"></p><div id="ppi-results" class="cards"></div><div class="toolbar"><button id="ppi-prev">이전</button><span id="ppi-page"></span><button id="ppi-next">다음</button></div>`;
 function ppiRows(){const cutoff=endingMonths(data.built?.slice(0,7),7)[0];return ppis.filter(i=>{
   if(ppiState.query&&!`${i.name} ${i.name_en} ${i.code} ${i.id}`.toLowerCase().includes(ppiState.query.toLowerCase()))return false;
   if(ppiState.country&&i.country!==ppiState.country)return false;
   if(ppiState.group&&i.group!==ppiState.group)return false;
   if(ppiState.category&&(i.category||i.group)!==ppiState.category)return false;
   if(ppiState.stale&&(!i.last_month||i.last_month<cutoff))return false;
   if(ppiState.favorite&&!ppiFavorites.includes(i.id))return false;
   if(['yoy','mom','qoq'].some(k=>ppiState[k]!==''&&(!finite(i[k])||i[k]<Number(ppiState[k]))))return false;
   if(ppiState.hot&&(!finite(i.yoy)||Math.abs(i.yoy)<Number(ppiState.threshold)))return false;
   if(Number(ppiState.acc)>0&&(!finite(i.acceleration)||i.acceleration<Number(ppiState.acc)))return false;
   if(ppiState.surge&&i.acceleration!==6)return false;
   return true;
 }).sort((a,b)=>{const k=ppiState.sort;if(k==='name')return ppiTitle(a).localeCompare(ppiTitle(b));if(k==='last_month')return String(b.last_month).localeCompare(String(a.last_month));const av=k==='abs_yoy'?Math.abs(a.yoy??NaN):a[k],bv=k==='abs_yoy'?Math.abs(b.yoy??NaN):b[k];return finite(av)&&finite(bv)?(ppiState.ascending?av-bv:bv-av):finite(av)?-1:finite(bv)?1:a.id.localeCompare(b.id);});}
 function renderPPI(){const rows=ppiRows(),pages=Math.max(1,Math.ceil(rows.length/80));ppiPage=Math.max(0,Math.min(ppiPage,pages-1));$('#ppi-count').textContent=`${fmt(rows.length)}개 / 전체 ${fmt(ppis.length)}개 · 최신 판정 기준 ${data.built}`;$('#ppi-page').textContent=`${ppiPage+1} / ${pages}`;$('#ppi-prev').disabled=ppiPage===0;$('#ppi-next').disabled=ppiPage>=pages-1;
 const target=$('#ppi-results');target.className=ppiState.layout==='cards'?'cards':'';
 if(ppiState.layout==='table'){target.innerHTML=`<div class="table-wrap"><table><thead><tr>${['국가 / 코드','계열','최근 월','값','YoY','MoM','QoQ','3M YoY','상승횟수 / 6','동작'].map(k=>`<th>${k}</th>`).join('')}</tr></thead><tbody>${rows.slice(ppiPage*80,(ppiPage+1)*80).map(i=>`<tr><td>${esc(i.country)} / ${esc(i.code)}</td><td>${esc(ppiTitle(i))}<br>${esc(i.unit)}</td><td>${esc(i.last_month)}</td><td>${fmt(i.series?.at(-1)?.value)}</td>${['yoy','mom','qoq','yoy3'].map(k=>`<td>${pct(i[k])}</td>`).join('')}<td>${fmt(i.acceleration)}</td><td><button data-action="ppi-detail" data-id="${esc(i.id)}">장기 이력</button><button data-ppi-favorite="${esc(i.id)}" aria-pressed="${ppiFavorites.includes(i.id)}">${ppiFavorites.includes(i.id)?'★':'☆'}</button></td></tr>`).join('')}</tbody></table></div>`;return;}
 target.innerHTML=rows.length?rows.slice(ppiPage*80,(ppiPage+1)*80).map(i=>`<article class="card ${finite(i.yoy)&&Math.abs(i.yoy)>=Number(ppiState.threshold)?'hot':''}"><small>${esc(i.country)} · ${esc(i.category||i.group||'분류 미제공')} · ${i.seasonally_adjusted?'계절조정':'계절조정 미표시'}</small><h3>${esc(ppiTitle(i))}</h3><p class="muted">${esc(i.code)} · ${esc(i.last_month||'—')} · ${esc(i.unit)}</p><div class="metrics"><span>YoY<strong>${pct(i.yoy)}</strong></span><span>MoM<strong>${pct(i.mom)}</strong></span><span>QoQ<strong>${pct(i.qoq)}</strong></span></div><p>최근 지수 ${fmt(i.series?.at(-1)?.value)} · 3M YoY ${pct(i.yoy3)} · 상승 ${fmt(i.acceleration)}/6</p>${sparkline(i.series)}<p>${i.source_kind==='phalanx_existing'?'기존 Phalanx':'참고 스냅샷'} · ${link(i.source_url,'출처')}</p><button data-action="ppi-detail" data-id="${esc(i.id)}">장기 이력</button> <button data-ppi-favorite="${esc(i.id)}" aria-pressed="${ppiFavorites.includes(i.id)}">${ppiFavorites.includes(i.id)?'★':'☆'} 관심</button></article>`).join(''):empty('조건에 맞는 PPI 계열이 없습니다. 최신자료 제외 또는 최소 증가율 조건을 조정하세요.');}
 const historyLoads=new Map();
 function loadHistory(i){if(window.STOCKMAP_HISTORY?.[i.id])return Promise.resolve();if(!i.history_path)return Promise.resolve();if(!/^ppi-history\/(local|(?:KR|US)-\d{2})\.js$/.test(i.history_path))return Promise.reject(new Error('이력 경로 오류'));if(historyLoads.has(i.history_path))return historyLoads.get(i.history_path);const promise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=i.history_path;s.onload=resolve;s.onerror=()=>{historyLoads.delete(i.history_path);s.remove();reject(new Error('이력 파일을 불러오지 못했습니다.'));};document.head.appendChild(s);});historyLoads.set(i.history_path,promise);return promise;}
 async function ppiDetail(i){open(`PPI · ${ppiTitle(i)}`,`<p>장기 이력을 불러오는 중입니다.</p>`);const id=i.id;$('#detail-dialog').dataset.ppi=id;try{await loadHistory(i);if(!$('#detail-dialog').open||$('#detail-dialog').dataset.ppi!==id)return;const full=window.STOCKMAP_HISTORY?.[id],points=Array.isArray(full)?full:full?.d?.map((m,n)=>({month:m,value:full.v[n]}))||i.series;
 $('#detail-body').innerHTML=`<p>${esc(i.country)} · ${i.source_kind==='phalanx_existing'?'기존 Phalanx':'참고 스냅샷'} · ${link(i.source_url,'출처')}</p><label>기간<select id="ppi-range"><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option><option value="0">전체 이력</option></select></label><div id="ppi-history-chart"></div>`;
 const draw=()=>{const all=cleanSeries(points),span=Number($('#ppi-range').value),ps=span?all.slice(-span):all,q=quarters(ps);$('#ppi-history-chart').innerHTML=`<p>${esc(ps[0]?.month||'—')} ~ ${esc(ps.at(-1)?.month||'—')} · ${fmt(ps.filter(p=>finite(p.value)).length)}개 관측</p>${chart([{name:ppiTitle(i),unit:i.unit||'단위 미제공',values:ps.map(p=>p.value)},{name:'YoY',unit:'%',values:ps.map(p=>growth(p.value,all.find(a=>a.month===String(Number(p.month.slice(0,4))-1)+p.month.slice(4))?.value))}],ps.map(p=>p.month),'PPI 지수와 YoY · 별도 단위 축')}<h3>완성 분기 평균</h3><p>3개월이 모두 관측된 분기만 계산합니다.</p><div class="table-wrap"><table><thead><tr><th>분기</th><th>평균</th><th>QoQ</th><th>YoY</th></tr></thead><tbody>${q.map((v,j)=>`<tr><td>${esc(v.quarter)}</td><td>${fmt(v.value)}</td><td>${pct(growth(v.value,q[j-1]?.value))}</td><td>${pct(growth(v.value,q[j-4]?.value))}</td></tr>`).join('')}</tbody></table></div>`;};$('#ppi-range').addEventListener('change',draw);draw();}catch(e){if($('#detail-dialog').dataset.ppi===id)$('#detail-body').textContent=e.message+' 최근 관측값은 목록에서 확인할 수 있습니다.';}}
 function drawPpiPresets(){$('#ppi-presets').innerHTML='<option value="">선택</option>'+ppiPresets.map((p,n)=>`<option value="${n}">${esc(p.name)}</option>`).join('');}
 $$('[data-ppi]').forEach(el=>el.addEventListener(el.type==='search'||el.type==='number'?'input':'change',()=>{ppiState[el.dataset.ppi]=el.type==='checkbox'?el.checked:el.value;ppiPage=0;renderPPI();}));
 function syncPpi(){$$('[data-ppi]').forEach(el=>{const v=ppiState[el.dataset.ppi];if(el.type==='checkbox')el.checked=!!v;else el.value=v??'';});ppiPage=0;renderPPI();}
 $('#ppi-prev').onclick=()=>{ppiPage--;renderPPI();};$('#ppi-next').onclick=()=>{ppiPage++;renderPPI();};$('#ppi-reset').onclick=()=>{ppiState={...ppiOptions};syncPpi();};
 $('#ppi-save').onclick=()=>{const name=$('#ppi-preset-name').value.trim();if(!name){say('PPI 조건 이름을 입력하세요.');return;}ppiPresets=ppiPresets.filter(p=>p.name!==name);ppiPresets.push({name,state:{...ppiState}});save('ppi-presets',ppiPresets);drawPpiPresets();say('PPI 조건을 저장했습니다.');};
 $('#ppi-load').onclick=()=>{const p=ppiPresets[$('#ppi-presets').value];if(p?.state){ppiState=ppiSavedState(p.state);syncPpi();}};$('#ppi-delete').onclick=()=>{const n=$('#ppi-presets').value;if(n==='')return;ppiPresets.splice(Number(n),1);save('ppi-presets',ppiPresets);drawPpiPresets();};
 function downloadCSV(name,rows){const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('#ppi-csv').onclick=()=>{const fields=['id','country','code','name','name_en','last_month','yoy','mom','qoq','unit','source_kind','source_url'];downloadCSV('ppi-filtered.csv',[fields,...ppiRows().map(i=>fields.map(k=>i[k]))]);};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-ppi-favorite]');if(!b)return;const id=b.dataset.ppiFavorite;ppiFavorites=ppiFavorites.includes(id)?ppiFavorites.filter(x=>x!==id):[...ppiFavorites,id];save('ppi-favorites',ppiFavorites);renderPPI();});drawPpiPresets();
 let workbookPage=0;
 const unmatchedRows=new Set(arr(data.unmatched_workbook_rows).map(r=>r.source_row));
 function workbookRows(){const q=$('#workbook-search').value.toLowerCase();return arr(data.workbook_rows).filter(r=>(!$('#workbook-unmatched').checked||unmatchedRows.has(r.source_row))&&(!q||Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))));}
 function renderWorkbook(){const rows=workbookRows(),pages=Math.max(1,Math.ceil(rows.length/80));workbookPage=Math.min(workbookPage,pages-1);const fields=['source_row',...Object.keys(data.workbook_rows?.[0]||{}).filter(k=>k!=='source_row')];$('#workbook-count').textContent=`${rows.length}행 / 원문 ${arr(data.workbook_rows).length}행 · 자동 연결 보류 ${unmatchedRows.size}행 · ${workbookPage+1}/${pages}쪽`;$('#workbook-results').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr>${fields.map(k=>`<th>${esc(k==='source_row'?'엑셀 행':k)}</th>`).join('')}</tr></thead><tbody>${rows.slice(workbookPage*80,(workbookPage+1)*80).map(r=>`<tr>${fields.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('일치하는 원문 행이 없습니다.');$('#workbook-prev').disabled=workbookPage===0;$('#workbook-next').disabled=workbookPage===pages-1;}
 $('#workbook-search').oninput=()=>{workbookPage=0;renderWorkbook();};$('#workbook-unmatched').onchange=()=>{workbookPage=0;renderWorkbook();};$('#workbook-prev').onclick=()=>{workbookPage--;renderWorkbook();};$('#workbook-next').onclick=()=>{workbookPage++;renderWorkbook();};$('#workbook-csv').onclick=()=>{const fields=Object.keys(data.workbook_rows?.[0]||{});downloadCSV('workbook-original.csv',[fields,...workbookRows().map(r=>fields.map(k=>r[k]))]);};
 function renderSources(){const summary=data.summary||{};$('#source-results').innerHTML=`<h3>수록 범위</h3><div class="cards">${[['종목',summary.stocks],['품목명',summary.products],['웹 원문 행',summary.items],['기존 대비 신규 기업',summary.new_companies],['신규 HS6',summary.new_hs6],['HS 없음',summary.missing_hs_rows],['판본 HS 변경',summary.changed_hs_rows],['판본 상태 변경',summary.changed_status_rows]].map(([k,v])=>`<article class="card"><small>${esc(k)}</small><h3>${fmt(v)}</h3></article>`).join('')}</div><h3>판본과 출처</h3><p>${link(data.reference?.url,'참고 웹')} · ${esc(data.reference?.built)} / 첨부 엑셀 ${esc(data.workbook?.date)}</p><p>원본 573행: 미검증 164 · 추정 243 · 체크 156 · 체크·근사 10. 이 중 ${fmt(summary.matched_workbook_rows)}행만 웹 판본과 유일하게 대응했습니다.</p><details><summary>원본 해시와 전체 통계</summary>${raw({built:data.built,reference:data.reference,workbook:data.workbook,summary})}</details><h3>7개국 공식 API 수집 현황</h3><p>참고 수치를 복사한 시계열과 직접 조회한 국가 총액은 구분합니다. 소스가 오류·빈 응답이면 관측값을 만들지 않습니다.</p><div class="cards">${arr(data.countries).map(c=>`<article class="card"><small>${esc(c.code)} · reporter ${esc(c.reporter)}</small><h3>${esc(c.name)}</h3><span class="badge">${esc(c.status)}</span><p>관측 ${fmt(c.observations)}개 · 최근 ${esc(c.latest_month||'없음')}<br>수집 대상 HS·방향 ${fmt(c.requested_pairs)}쌍</p><p>${esc(c.notes)}</p><p>${link(c.source_url,'공식 API 문서')}</p><details><summary>요청·응답 근거</summary>${raw(c.last_attempt||'조회 기록 없음')}</details></article>`).join('')}</div><h3>반영 상태</h3>${arr(data.features).map(f=>`<p><strong>${esc(f.name)} · ${esc(f.status)}</strong><br>${esc(f.note)}</p>`).join('')}<p>결측은 — 또는 선의 간격으로 보존합니다. PPI QoQ는 완전한 달력 분기 3개월 평균, 3M YoY는 최근 3개월 합계의 전년비, 상승 횟수는 최근 6번의 월간 비교 중 증가한 횟수입니다. 날짜 차이로 검증상태를 승격하지 않습니다.</p>`;}

 function syncControls(){$$('[data-filter]').forEach(el=>{const v=state[el.dataset.filter];if(el.type==='checkbox')el.checked=!!v;else el.value=v;});}
 function render(updateURL=true){syncControls();for(const v of ['stocks','ppi','compare','sources','workbook'])$('#'+v+'-view').hidden=state.view!==v;$('#filters').hidden=state.view!=='stocks';$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===state.view)));if(state.view==='stocks')renderStocks();if(state.view==='ppi')renderPPI();if(state.view==='compare')renderCompare();if(state.view==='sources')renderSources();if(state.view==='workbook')renderWorkbook();if(updateURL){try{const q=stateQuery(state);window.history.replaceState(null,'',location.pathname+(q?'?'+q:'')+location.hash);}catch{say('이 환경에서는 주소 갱신이 제한됩니다. 필터는 현재 화면에서 적용됩니다.');}}}
 function renderPresets(){$('#presets').innerHTML='<option value="">선택</option>'+presets.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');}
 $$('[data-filter]').forEach(el=>el.addEventListener(el.type==='search'?'input':'change',()=>{state[el.dataset.filter]=el.type==='checkbox'?el.checked:el.value;render();}));
 $$('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;render();}));
 document.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const id=b.dataset.id,i=items.find(v=>String(v.id)===id);if(b.dataset.action==='ppi-detail'){const p=ppis.find(v=>String(v.id)===id);if(p)ppiDetail(p);return;}if(!i)return;if(b.dataset.action==='detail'){detail(i);return;}if(b.dataset.action==='favorite'){favorites=favorites.includes(id)?favorites.filter(v=>v!==id):[...favorites,id];save('favorites',favorites);}if(['compare','remove-compare'].includes(b.dataset.action)){if(selected.includes(id))selected=selected.filter(v=>v!==id);else if(selected.length<4)selected.push(id);else{say('비교는 최대 4개입니다. 먼저 한 항목을 해제하세요.');return;}say(`비교 항목 ${selected.length}/4개`);}const action=b.dataset.action;render();const replacement=$$('button[data-action]').find(n=>n.dataset.id===id&&n.dataset.action===action);replacement?.focus();});
 $('#close-dialog').addEventListener('click',()=>$('#detail-dialog').close());$('#detail-dialog').addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
 $('#detail-dialog').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...$('#detail-dialog').querySelectorAll('button,a[href],input,select,summary,[tabindex="0"]')].filter(n=>n.getClientRects().length&&!n.disabled),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}});
 $('#theme-toggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;save('theme',next);});
 $('#reset-filters').addEventListener('click',()=>{state={...defaults};render();});
 $('#save-preset').addEventListener('click',()=>{const name=$('#preset-name').value.trim();if(!name){say('저장할 조건 이름을 입력하세요.');return;}presets=presets.filter(p=>p.name!==name);presets.push({name,state:{...state}});save('presets',presets);renderPresets();say('조건을 저장했습니다.');});
 $('#load-preset').addEventListener('click',()=>{const p=presets[$('#presets').value];if(p?.state){state=stateFrom(new URLSearchParams(stateQuery({...defaults,...p.state})));render();}});
 $('#delete-preset').addEventListener('click',()=>{const idx=$('#presets').value;if(idx==='')return;presets.splice(Number(idx),1);save('presets',presets);renderPresets();});
 $('#export-csv').addEventListener('click',()=>{const fields=['id','sym','name','market','cap','o2','flow','product','label','hs6','st','vstatus','latest_ym','latest','yoy','mom','qoq','yoy3','src'];const rows=filterRows(items,state,favorites);const content=[fields.concat(['workbook_status','reference_date','workbook_date','trade_unit']).map(csvCell).join(','),...rows.map(i=>fields.map(k=>i[k]).concat([i.workbook?.status,data.reference?.built,data.workbook?.date,'USD thousand']).map(csvCell).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='stockmap-filtered.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say(`${rows.length}개 항목의 CSV를 생성했습니다.`);});
 $('#compare-kind').addEventListener('change',renderCompare);window.addEventListener('popstate',()=>{state=stateFrom(new URLSearchParams(location.search));render(false);});renderPresets();render(false);
}
