const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const e=require('../cloud_signals.js');
const ledger=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../data/cloud_signals/ledger.json')));
function row(extra={}){return Object.assign({id:'1',key:'1',revision:1,provider:'TEST',metric:'growth',axis:'demand',period:'2026-Q2',value:2,unit:'%',scope:'cloud',evidence:'confirmed',verified:true,verified_at:'2026-09-10',observed_at:'2026-09-10',published_at:'2026-08-01',effective_at:'2026-06-30',direction:1,rule:'increase',source_url:'https://www.sec.gov/a',origin:'reviewed',correlation_group:'earnings'},extra);}
const a=row(),b=row({id:'2',key:'2',metric:'profit',axis:'pricing',correlation_group:'profit'});
test('missing data has no neutral score',()=>{assert.equal(e.ensemble([],'TEST','2026-09-10').score,null);assert.equal(e.ensemble([a],'TEST','2026-09-10').score,null);});
test('known axes produce partial coverage',()=>{const r=e.ensemble([a,b],'TEST','2026-09-10');assert.equal(r.score,100);assert.equal(r.coverage,45);assert.equal(r.axis_count,2);assert.equal(r.source_count,1);});
test('zero is valid, not missing',()=>{assert.equal(e.excluded(row({value:0,direction:0}),'2026-09-10'),null);});
test('unverified, targets, inferred and missing directions excluded',()=>{for(const extra of [{verified:false},{evidence:'target'},{evidence:'inference'},{direction:null},{source_url:'javascript:alert(1)'},{direction:NaN}])assert.ok(e.excluded(row(extra),'2026-09-10'));});
test('no lookahead before first collection or publication or verification',()=>{assert.equal(e.ensemble([a,b],'TEST','2026-09-09').score,null);for(const key of ['observed_at','published_at','verified_at','effective_at'])assert.ok(e.excluded(row({[key]:'2026-09-11'}),'2026-09-10'));});
test('stale observations expire',()=>{assert.ok(e.excluded(row({effective_at:'2026-01-01'}),'2026-09-10'));});
test('revisions do not double count, historical asof sees original',()=>{const v2=row({id:'v2',revision:2,direction:-1,observed_at:'2026-09-11'});assert.equal(e.current([a,v2],'2026-09-10')[0].id,'1');assert.equal(e.current([a,v2],'2026-09-11')[0].id,'v2');});
test('same source group is averaged, never amplified',()=>{const dup=row({id:'copy',key:'copy',metric:'second_growth'});assert.equal(e.ensemble([a,b,dup],'TEST','2026-09-10').score,e.ensemble([a,b],'TEST','2026-09-10').score);assert.equal(e.ensemble([a,b,dup],'TEST','2026-09-10').axes.demand.groups,1);});
test('latest metric replaces its previous period',()=>{const newer=row({id:'3',key:'3',period:'2026-Q3',effective_at:'2026-08-31',direction:-1});const r=e.ensemble([a,b,newer],'TEST','2026-09-10');assert.equal(r.axes.demand.direction,-1);assert.ok(r.conflict);});
test('filters compose without changing the ensemble',()=>{assert.equal(e.filtered([a,b],{provider:'TEST',axis:'demand'}).length,1);assert.equal(e.filtered([a],{search:'NOT FOUND'}).length,0);});
test('CSV escapes cells and spreadsheet formulas',()=>{const s=e.csv([{x:'=HYPERLINK("bad")',y:'a,b\nc'}],['x','y']);assert.ok(s.includes("'=HYPERLINK"));assert.ok(s.includes('"a,b\nc"'));});
test('actual provider universe and known semantic guards',()=>{assert.equal(Object.keys(ledger.providers).length,22);for(const id of Object.keys(ledger.providers)){const r=e.ensemble(ledger.signals,id,'2026-09-10');assert.ok(r.score===null||(r.score>=0&&r.score<=100));assert.ok(r.used_ids.every(k=>ledger.signals.find(s=>s.id===k).verified));}assert.ok(e.ensemble(ledger.signals,'CRWV','2026-09-10').conflict);assert.equal(e.ensemble(ledger.signals,'LAMBDA','2026-09-10').score,null);assert.equal(e.ensemble(ledger.signals,'MSFT','2026-09-10').axes.contracts,null);});
